library(ggvis)

server <- function(input, output) {
  
  
  x = matrix(c(40,20,30,15),2,2)
  
  y = data.frame(FAILURE = c("X","30"),PASS = c("20","10"))
  row.names(y) = c("SAS","SATA")
  
  output$y = renderTable({y})
  
  
  p=c()
  
  for(i in 1:150){
    x[1,1] = i 
    p[i] =  chisq.test(x)$p.value
  }
  
  
  p2 = c()
  
  for(i in 1:150){
    x[1,1] = i 
    p2[i] =  fisher.test(x)$p.value
  }
  
  
  
  simu.chisq = c()
  for(i in 1:150){
    x[1,1] = i 
    simu.chisq[i] =  chisq.test(x,simulate.p.value = TRUE,B = 1000)$p.value
  }
  
  
  
  
  
  
  
  simu.fisher = c()
  for(i in 1:150){
    x[1,1] = i 
    simu.fisher[i] =  fisher.test(x,simulate.p.value = TRUE,B = 1000)$p.value
  }
  
  
  
  output$x = renderPlot({
    plot(x=1:150,y=p,type="l",main="P-value Behaviors Comparison"
         ,xlab = "X"
         ,ylab = "P-value",lwd=1
    )
    lines(1:150,p2,col="red",lty=1,lwd=1)
    
    lines(1:150,simu.chisq,col="blue",lty=3,lwd=1)
    
    abline(h=0.05,lty=2)
    
    abline(v=40,lty=2)
    text(0,0.08,"0.05")
    text(44,0,"X = 40")
    legend(110, 1, c("P-value of Chisq Test ", "P-value of Fisher's Exact Test", "P-value generated by Simulation"), col = c("black","red", "blue"),
           text.col = c("black","red", "blue"), lty = c(1, 1, 3),
           merge = TRUE, bg = "gray90",bty="n")
  })
  
  #####################################################2
  
  y2 = data.frame(FAILURE = c("X","10"),PASS = c("30","60"))
  row.names(y2) = c("SAS","SATA")
  
  output$y2 = renderTable({y2})
  
  output$x2 = renderPlot({
    x = matrix(c(70,10,30,60),2,2)
    
    
    
    
    p=c()
    
    for(i in 1:150){
      x[1,1] = i 
      p[i] =  chisq.test(x)$p.value
    }
    
    
    p2 = c()
    
    for(i in 1:150){
      x[1,1] = i 
      p2[i] =  fisher.test(x)$p.value
    }
    
    
    
    simu.chisq = c()
    for(i in 1:150){
      x[1,1] = i 
      simu.chisq[i] =  chisq.test(x,simulate.p.value = TRUE,B = 1000)$p.value
    }
    
    
    simu.fisher = c()
    for(i in 1:150){
      x[1,1] = i 
      simu.fisher[i] =  fisher.test(x,simulate.p.value = TRUE,B = 1000)$p.value
    }
    
    plot(x=1:150,y=p,type="l",main="P-value Behaviors Comparison"
         ,xlab = "X"
         ,ylab = "P-value",lwd=1
    )
    lines(1:150,p2,col="red",lty=1,lwd=1)
    
    lines(1:150,simu.chisq,col="blue",lty=3,lwd=1)
    
    abline(h=0.05,lty=2)
    
    abline(v=5,lty=2)
    text(0,0.08,"0.05")
    text(5,0,"X = 5")
    legend(110, 1, c("P-value of Chisq Test ", "P-value of Fisher's Exact Test", "P-value generated by Simulation"), col = c("black","red", "blue"),
           text.col = c("black","red", "blue"), lty = c(1, 1, 3),
           merge = TRUE, bg = "gray90",bty="n")
  })
  
  #########################3
  y3 = data.frame(FAILURE = c("X","30"),PASS = c("20","0"))
  row.names(y3) = c("SAS","SATA")
  
  output$y3 = renderTable({y3})
  
  output$x3 = renderPlot({
    x = matrix(c(70,30,20,0),2,2)
    
    
    
    
    p=c()
    
    for(i in 1:150){
      x[1,1] = i 
      p[i] =  chisq.test(x)$p.value
    }
    
    
    p2 = c()
    
    for(i in 1:150){
      x[1,1] = i 
      p2[i] =  fisher.test(x)$p.value
    }
    
    
    
    simu.chisq = c()
    for(i in 1:150){
      x[1,1] = i 
      simu.chisq[i] =  chisq.test(x,simulate.p.value = TRUE,B = 1000)$p.value
    }
    
    
    simu.fisher = c()
    for(i in 1:150){
      x[1,1] = i 
      simu.fisher[i] =  fisher.test(x,simulate.p.value = TRUE,B = 1000)$p.value
    }
    
    plot(x=1:150,y=p,type="l",main="P-value Behaviors Comparison"
         ,xlab = "X"
         ,ylab = "P-value",lwd=1
    )
    lines(1:150,p2,col="red",lty=1,lwd=1)
    
    lines(1:150,simu.chisq,col="blue",lty=3,lwd=1)
    
    abline(h=0.05,lty=2)
    
    
    text(0,0.055,"0.05")
    
    legend(1, 0.1, c("P-value of Chisq Test ", "P-value of Fisher's Exact Test", "P-value generated by Simulation"), col = c("black","red", "blue"),
           text.col = c("black","red", "blue"), lty = c(1, 1, 3),
           merge = TRUE, bg = "gray90",bty="n")
  })
  
}

ui <- fluidPage(
  br(),
  h4("Understanding the behavior of the p values of Chisquare Test of Independence"),
  hr(),
  fluidRow(
    column(2,p("Contingency Table 1"),tableOutput("y")),
    column(10,plotOutput("x",height="550px"))
  ),
  hr(),
  fluidRow(
    column(2,p("Contingency Table 2"),tableOutput("y2")),
    column(10,plotOutput("x2",height="550px"))
  ),
  hr(),
  fluidRow(
    column(2,p("Contingency Table 3"),tableOutput("y3")),
    column(10,plotOutput("x3",height="550px"))
  )
  
)

shinyApp(ui = ui, server = server)